---
- name: Instalar httpd
  yum:
    name: httpd
    state: latest

- name: Start e enable o servico httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: Verificar se o diretoio vhost esta presente
  file:
    path: "/var/www/vhosts/{{ ansible_hostname }}"
    state: directory

- name: Entregar conte√∫do html
  copy:
    src: index.html
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: Template arquivo vhost
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_httpd


